name: tao-ped2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - git
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - matplotlib
  - pillow
  - opencv
  - faiss-cpu
  - pip:
      - --index-url https://download.pytorch.org/whl/cu130
      - --extra-index-url https://pypi.org/simple
      - torch==2.10.0
      - torchvision==0.25.0
      - ftfy
      - regex
      - git+https://github.com/openai/CLIP.git
